/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#006c49",
        "on-primary": "#ffffff",
        "primary-container": "#10b981",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        secondary: "#855300",
        "on-secondary": "#ffffff",
        "secondary-container": "#fea619",
        "on-secondary-container": "#684000",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        tertiary: "#b91a24",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ff7a73",
        "on-tertiary-container": "#79000e",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-fixed-variant": "#930013",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#fff8f5",
        "surface-dim": "#e2d8d2",
        "surface-bright": "#fff8f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fcf2eb",
        "surface-container": "#f6ece6",
        "surface-container-high": "#f0e6e0",
        "surface-container-highest": "#eae1da",
        "on-surface": "#1f1b17",
        "on-surface-variant": "#3c4a42",
        outline: "#6c7a71",
        "outline-variant": "#bbcabf",
        background: "#fff8f5",
        "on-background": "#1f1b17",
        "inverse-surface": "#342f2b",
        "inverse-on-surface": "#f9efe8",
        "inverse-primary": "#4edea3",
        "surface-tint": "#006c49",
      },
      fontFamily: {
        display: ["Geist Sans", "sans-serif"],
        "headline-lg": ["Geist Sans", "sans-serif"],
        "headline-md": ["Geist Sans", "sans-serif"],
        "headline-sm": ["Geist Sans", "sans-serif"],
        "label-md": ["Geist Sans", "sans-serif"],
        "label-sm": ["Geist Sans", "sans-serif"],
        body: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        soft: "0 1px 3px rgba(0,0,0,0.05)",
        card: "0 18px 50px -24px rgba(5, 46, 22, 0.15)",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "24px",
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
